sudo: false

language: python

python:
    - "3.6"

install:
    - pip install ads titlecase tqdm matplotlib

addons:
    apt:
        packages:
            - texlive-xetex
            - texlive-latex-recommended
            - texlive-latex-extra
            - texlive-fonts-recommended
            - texlive-fonts-extra
            - latex-xcolor
            - lmodern

script:
    - make

after_success: |
    cd $TRAVIS_BUILD_DIR
    git checkout --orphan $TRAVIS_BRANCH-pdf
    git rm -rf . > /dev/null 2>&1
    cp cv.pdf luger_cv.pdf
    git add -f luger_cv.pdf cv.pdf cv_nopubs.pdf cv_onepage.pdf publications.pdf
    git add -f pubs.json metrics.json stars.json citedates.txt
    git -c user.name='travis' -c user.email='travis' commit -m "rebuild pdf"
    git push -q -f https://$GITHUB_USER:$GITHUB_API_KEY@github.com/$TRAVIS_REPO_SLUG $TRAVIS_BRANCH-pdf > /dev/null 2>&1
